"""The C5 cocycle instrument: extension precompute (I-21) and the cocycle
probe/ablation/fit (I-22/I-22b), T8.

This is the one instrument built for a single claim -- C5, the
``(48,29)`` GL(2,3) [split] vs ``(48,28)`` SL(2,3).C2 [non-split] contrast --
and it carries C5's scoped risk (a null probe/ablation ships as a measurement).

The object is an extension ``1 -> N -> G -> Q -> 1`` for a pre-registered normal
subgroup ``N`` (``Q = G/N``). Fix a transversal ``s: Q -> G`` with ``s(e) = e``.
Every ``g`` in ``G`` then has coordinates ``(n, q)`` with ``g = n . s(q)``,
``n in N``, ``q = coset(g)``, and the product law is the *twisted rule*

    (n1, q1) . (n2, q2) = (n1 . phi_{q1}(n2) . f(q1, q2),  q1 q2),

where ``phi_q(n) = s(q) n s(q)^{-1}`` is the action of ``Q`` on ``N`` and
``f(q1, q2) = s(q1) s(q2) s(q1 q2)^{-1} in N`` is the 2-cocycle (factor set).
Dropping ``f`` gives the *untwisted* (semidirect) rule. Two self-verifying
identities are asserted, never assumed:

* the (possibly non-abelian) cocycle identity
  ``f(a,b) f(ab,c) == phi_a(f(b,c)) f(a,bc)`` for all ``a,b,c in Q`` -- this is
  associativity of ``G`` re-expressed in coordinates;
* ``f == e`` is achievable by *some* transversal iff the extension *splits*
  (a complement to ``N`` exists). This is the crux of the split/non-split
  contrast: the untwisted rule reproduces the full Cayley table exactly iff a
  trivialising transversal exists, so the ``f == 1`` fit SUCCEEDS on a split
  group and FAILS on a non-split one, for *every* transversal.

On a split member the cocycle probe is degenerate by construction: with the
complement transversal ``f`` is constant, so the decode target has no variation
(the split member's control is a fit residual, not a probe score).

The model-facing probe (I-22) decodes ``f(q1, q2)`` held out over ``(q1, q2)``
cells -- never over ``(a, b)`` pairs, because many pairs share one cell and an
``(a, b)`` split would be pseudoreplication (banned practice 6). The ablation
(I-22b) removes the ``f``-carrying direction and is what licenses "the model
uses the cocycle"; a norm- and dimension-matched random subspace is the control
(I-03).

Pure group theory here uses only the exported Cayley table and never Sage/GAP.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import torch

from ..groups.group import FiniteGroup
from ..model import GroupModel
from .occupancy import cayley_grid_tokens

_TOL = 1e-9


# ---------------------------------------------------------------------------
# Cayley-table primitives (index arithmetic only; no group discovery)
# ---------------------------------------------------------------------------


def _identity_index(table: np.ndarray) -> int:
    n = table.shape[0]
    idx = np.arange(n)
    candidates = np.flatnonzero(np.all(table == idx[None, :], axis=1))
    if candidates.size == 0:
        raise ValueError("Cayley table has no identity element")
    return int(candidates[0])


def _inverses(table: np.ndarray, identity: int) -> np.ndarray:
    n = table.shape[0]
    inverses = np.empty(n, dtype=np.int64)
    for g in range(n):
        inverses[g] = int(np.flatnonzero(table[g] == identity)[0])
    return inverses


def is_subgroup(table: np.ndarray, members: np.ndarray) -> bool:
    """``members`` is closed under the product and inversion and contains the
    identity -- a subgroup. Pure index arithmetic on the Cayley table."""
    elems = sorted(int(x) for x in np.asarray(members).tolist())
    if not elems:
        return False
    subset = set(elems)
    identity = _identity_index(table)
    if identity not in subset:
        return False
    for a in elems:
        for b in elems:
            if int(table[a, b]) not in subset:
                return False
    return True


def is_normal(table: np.ndarray, members: np.ndarray) -> bool:
    """``members`` is a normal subgroup: a subgroup with ``g N g^{-1} = N`` for
    every ``g`` in ``G``."""
    if not is_subgroup(table, members):
        return False
    identity = _identity_index(table)
    inverses = _inverses(table, identity)
    subset = {int(x) for x in np.asarray(members).tolist()}
    n = table.shape[0]
    for g in range(n):
        for h in subset:
            if int(table[table[g, h], inverses[g]]) not in subset:
                return False
    return True


def subgroup_closure(table: np.ndarray, generators: set[int]) -> frozenset[int]:
    """The subgroup generated by ``generators`` (product closure including the
    identity), by breadth-first multiplication over the Cayley table."""
    identity = _identity_index(table)
    members = {identity, *(int(g) for g in generators)}
    frontier = list(members)
    while frontier:
        a = frontier.pop()
        for b in list(members):
            for prod in (int(table[a, b]), int(table[b, a])):
                if prod not in members:
                    members.add(prod)
                    frontier.append(prod)
    return frozenset(members)


# ---------------------------------------------------------------------------
# I-21: quotient, transversal, action, cocycle
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Extension:
    """The extension ``1 -> N -> G -> Q -> 1`` coordinatised by one transversal.

    ``normal`` are the sorted element indices of ``N``; ``n_local`` maps a global
    element index in ``N`` to its position ``0..|N|-1``. ``coset_label`` maps every
    element of ``G`` to its ``Q``-label (the ``N``-coset it lies in), with the
    identity coset labelled ``0``. ``quotient_table`` is ``Q``'s multiplication.
    ``transversal[q]`` is ``s(q)`` (a global index; ``s(0)`` is the identity).
    ``action[q]`` is ``phi_q`` as a permutation of ``N`` in local indices.
    ``cocycle[q1, q2]`` is ``f(q1, q2)`` as a local ``N`` index.
    """

    order: int
    normal: tuple[int, ...]
    quotient_order: int
    coset_label: np.ndarray  # [|G|] -> Q-label
    quotient_table: np.ndarray  # [|Q|, |Q|]
    transversal: np.ndarray  # [|Q|] -> global element index
    action: np.ndarray  # [|Q|, |N|] local permutation
    cocycle: np.ndarray  # [|Q|, |Q|] local N index
    n_local: dict[int, int]

    @property
    def normal_order(self) -> int:
        return len(self.normal)

    def to_record(self) -> dict[str, Any]:
        return {
            "order": self.order,
            "normal_order": self.normal_order,
            "quotient_order": self.quotient_order,
            "cocycle_trivial": bool(cocycle_is_trivial(self)),
            "transversal": self.transversal.tolist(),
            "cocycle": self.cocycle.tolist(),
        }


def _quotient(table: np.ndarray, normal: np.ndarray) -> tuple[np.ndarray, list[list[int]], int]:
    """Left cosets ``gN`` as ``Q``-labels, the identity coset labelled ``0``.

    Returns ``(coset_label, coset_members, quotient_order)``.
    """
    n = table.shape[0]
    members = sorted(int(x) for x in np.asarray(normal).tolist())
    identity = _identity_index(table)
    coset_label = -np.ones(n, dtype=np.int64)
    coset_members: list[list[int]] = []
    # Process the identity first so its coset (== N) is label 0.
    order = [identity] + [g for g in range(n) if g != identity]
    for g in order:
        if coset_label[g] >= 0:
            continue
        coset = sorted({int(table[g, h]) for h in members})
        label = len(coset_members)
        for x in coset:
            coset_label[x] = label
        coset_members.append(coset)
    return coset_label, coset_members, len(coset_members)


def build_extension(
    group: FiniteGroup,
    normal: np.ndarray,
    transversal: np.ndarray | None = None,
) -> Extension:
    """I-21: coordinatise ``G`` over a normal subgroup ``N`` with a transversal.

    ``transversal`` maps each ``Q``-label to a representative of that coset;
    ``s(0)`` must be the identity. When ``None`` a canonical transversal is used
    (the smallest element index of each coset, with the identity for coset 0).

    Asserts the extension identities: ``N`` is normal; the transversal picks one
    element per coset with ``s(0) = e``; the action lands in ``N``; the cocycle
    lands in ``N`` and is normalised (``f(0, q) = f(q, 0) = e``); and the
    non-abelian cocycle identity holds.
    """
    table = group.cayley_table
    members = np.asarray(normal, dtype=np.int64)
    if not is_normal(table, members):
        raise ValueError("the given subgroup is not normal in G; no extension is defined")
    identity = _identity_index(table)
    inverses = _inverses(table, identity)
    normal_sorted = tuple(sorted(int(x) for x in members.tolist()))
    n_local = {g: i for i, g in enumerate(normal_sorted)}
    normal_array = np.array(normal_sorted, dtype=np.int64)

    coset_label, coset_members, quotient_order = _quotient(table, members)

    if transversal is None:
        chosen = np.empty(quotient_order, dtype=np.int64)
        for label, coset in enumerate(coset_members):
            chosen[label] = identity if label == 0 else min(coset)
    else:
        chosen = np.asarray(transversal, dtype=np.int64).copy()
        if chosen.shape != (quotient_order,):
            raise ValueError(
                f"transversal must have one representative per coset ({quotient_order})"
            )
        seen_labels = coset_label[chosen]
        if sorted(seen_labels.tolist()) != list(range(quotient_order)):
            raise ValueError("transversal representatives do not cover the cosets exactly once")
        if int(chosen[0]) != identity:
            raise ValueError("transversal must satisfy s(0) = e (the identity coset)")

    # Quotient multiplication (well-defined by normality; read off the reps).
    quotient_table = np.empty((quotient_order, quotient_order), dtype=np.int64)
    for qi in range(quotient_order):
        for qj in range(quotient_order):
            quotient_table[qi, qj] = int(coset_label[table[chosen[qi], chosen[qj]]])

    # Action phi_q(n) = s(q) n s(q)^{-1}, as a local permutation of N.
    action = np.empty((quotient_order, len(normal_sorted)), dtype=np.int64)
    for q in range(quotient_order):
        s_q, s_q_inv = int(chosen[q]), int(inverses[chosen[q]])
        for i, g in enumerate(normal_sorted):
            image = int(table[table[s_q, g], s_q_inv])
            if image not in n_local:
                raise ValueError("action does not preserve N; the subgroup is not normal")
            action[q, i] = n_local[image]

    # Cocycle f(qi, qj) = s(qi) s(qj) s(qi qj)^{-1} in N (local index).
    cocycle = np.empty((quotient_order, quotient_order), dtype=np.int64)
    for qi in range(quotient_order):
        for qj in range(quotient_order):
            qk = int(quotient_table[qi, qj])
            value = int(table[table[chosen[qi], chosen[qj]], inverses[chosen[qk]]])
            if value not in n_local:
                raise ValueError("cocycle value fell outside N; transversal is inconsistent")
            cocycle[qi, qj] = n_local[value]

    extension = Extension(
        order=group.order,
        normal=normal_sorted,
        quotient_order=quotient_order,
        coset_label=coset_label,
        quotient_table=quotient_table,
        transversal=chosen,
        action=action,
        cocycle=cocycle,
        n_local=n_local,
    )
    _assert_normalised(extension)
    _assert_cocycle_identity(extension, table, normal_array)
    return extension


def _n_mul_local(table: np.ndarray, normal_array: np.ndarray, i: int, j: int) -> int:
    """Product of two ``N`` elements (given by local index), as a local index."""
    prod = int(table[normal_array[i], normal_array[j]])
    return int(np.flatnonzero(normal_array == prod)[0])


def _assert_normalised(extension: Extension) -> None:
    zero = extension.n_local[_identity_from_normal(extension)]
    q = extension.quotient_order
    if not all(int(extension.cocycle[0, j]) == zero for j in range(q)):
        raise ValueError("cocycle is not normalised: f(0, q) != e")
    if not all(int(extension.cocycle[i, 0]) == zero for i in range(q)):
        raise ValueError("cocycle is not normalised: f(q, 0) != e")


def _identity_from_normal(extension: Extension) -> int:
    """The identity's global index. ``s(0) = e`` by construction and ``e in N``."""
    return int(extension.transversal[0])


def _assert_cocycle_identity(
    extension: Extension, table: np.ndarray, normal_array: np.ndarray
) -> None:
    """``f(a,b) f(ab,c) == phi_a(f(b,c)) f(a,bc)`` for all ``a, b, c`` in ``Q``."""
    q = extension.quotient_order
    qt = extension.quotient_table
    f = extension.cocycle
    action = extension.action
    for a in range(q):
        for b in range(q):
            ab = int(qt[a, b])
            for c in range(q):
                bc = int(qt[b, c])
                lhs = _n_mul_local(table, normal_array, int(f[a, b]), int(f[ab, c]))
                phi_a_fbc = int(action[a, int(f[b, c])])
                rhs = _n_mul_local(table, normal_array, phi_a_fbc, int(f[a, bc]))
                if lhs != rhs:
                    raise ValueError(
                        f"cocycle identity fails at (a,b,c)=({a},{b},{c}): {lhs} != {rhs}"
                    )


def cocycle_is_trivial(extension: Extension) -> bool:
    """Whether ``f == e`` for this transversal (the untwisted rule is exact)."""
    zero = extension.n_local[int(extension.transversal[0])]
    return bool(np.all(extension.cocycle == zero))


# ---------------------------------------------------------------------------
# Coordinate rule and the f == 1 fit
# ---------------------------------------------------------------------------


def coordinates(extension: Extension, table: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Each element's coordinates ``(n, q)`` with ``g = n . s(q)``.

    Returns ``(n_local_of, q_of)`` arrays over ``0..|G|-1``. Asserts the map
    ``G -> N x Q`` is a bijection.
    """
    identity = _identity_index(table)
    inverses = _inverses(table, identity)
    normal_array = np.array(extension.normal, dtype=np.int64)
    q_of = extension.coset_label.copy()
    n_of = np.empty(extension.order, dtype=np.int64)
    for g in range(extension.order):
        q = int(q_of[g])
        n_elem = int(table[g, inverses[int(extension.transversal[q])]])
        slot = np.flatnonzero(normal_array == n_elem)
        if slot.size == 0:
            raise ValueError("coordinate decomposition left N; transversal is inconsistent")
        n_of[g] = int(slot[0])
    pairs = {(int(n_of[g]), int(q_of[g])) for g in range(extension.order)}
    if len(pairs) != extension.order:
        raise ValueError("coordinate map G -> N x Q is not a bijection")
    return n_of, q_of


def coordinate_product_accuracy(
    extension: Extension, table: np.ndarray, *, include_cocycle: bool
) -> float:
    """Fraction of ordered pairs ``(g1, g2)`` the coordinate rule reproduces.

    With ``include_cocycle=True`` this is the twisted rule and is exact (1.0) by
    construction. With ``include_cocycle=False`` this is the untwisted
    (semidirect) rule; it equals 1.0 iff ``f == e`` for this transversal.
    """
    normal_array = np.array(extension.normal, dtype=np.int64)
    n_of, q_of = coordinates(extension, table)
    transversal = extension.transversal
    action = extension.action
    cocycle = extension.cocycle
    qt = extension.quotient_table
    correct = 0
    total = extension.order * extension.order
    for g1 in range(extension.order):
        n1, q1 = int(n_of[g1]), int(q_of[g1])
        for g2 in range(extension.order):
            n2, q2 = int(n_of[g2]), int(q_of[g2])
            phi = int(action[q1, n2])
            n_res = _n_mul_local(table, normal_array, n1, phi)
            if include_cocycle:
                n_res = _n_mul_local(table, normal_array, n_res, int(cocycle[q1, q2]))
            qk = int(qt[q1, q2])
            predicted = int(table[normal_array[n_res], int(transversal[qk])])
            if predicted == int(table[g1, g2]):
                correct += 1
    return correct / total


@dataclass(frozen=True)
class SplitResult:
    """The split/non-split determination and, when split, a complement."""

    splits: bool
    complement: tuple[int, ...] | None
    quotient_order: int
    method: str

    def to_record(self) -> dict[str, Any]:
        return {
            "splits": self.splits,
            "complement": None if self.complement is None else list(self.complement),
            "quotient_order": self.quotient_order,
            "method": self.method,
        }


def _find_complement(table: np.ndarray, normal: np.ndarray) -> tuple[int, ...] | None:
    """A complement ``C`` to ``N``: a subgroup with ``|C| = [G:N]`` and
    ``C intersect N = {e}``, found by backtracking closure. ``None`` when the
    extension does not split.

    A complement is exactly a set of coset representatives closed under the
    product, so growth is pruned hard: any candidate whose closure revisits a
    coset or re-enters ``N`` nontrivially is rejected immediately.
    """
    identity = _identity_index(table)
    coset_label, coset_members, quotient_order = _quotient(table, normal)
    normal_set = {int(x) for x in np.asarray(normal).tolist()}
    target = quotient_order

    def covered(members: frozenset[int]) -> set[int]:
        return {int(coset_label[g]) for g in members}

    def valid(members: frozenset[int]) -> bool:
        labels = [int(coset_label[g]) for g in members]
        if len(set(labels)) != len(labels):
            return False  # two elements in one coset
        if any(g in normal_set and g != identity for g in members):
            return False  # re-entered N off the identity
        return True

    start = frozenset({identity})

    def search(current: frozenset[int], seen: set[frozenset[int]]) -> tuple[int, ...] | None:
        if len(current) == target:
            return tuple(sorted(current))
        have = covered(current)
        for label in range(quotient_order):
            if label in have:
                continue
            for x in coset_members[label]:
                grown = subgroup_closure(table, set(current) | {x})
                if not valid(grown) or grown in seen:
                    continue
                seen.add(grown)
                result = search(grown, seen)
                if result is not None:
                    return result
            # Committing to cover this (smallest uncovered) coset and failing
            # means no complement extends ``current``.
            break
        return None

    return search(start, {start})


def split_status(group: FiniteGroup, normal: np.ndarray) -> SplitResult:
    """Decide whether ``G`` splits over ``N`` -- equivalently, whether ``f == e``
    is achievable by some transversal (I-21's ``f == 1 iff split`` invariant)."""
    if not is_normal(group.cayley_table, normal):
        raise ValueError("the given subgroup is not normal in G")
    complement = _find_complement(group.cayley_table, np.asarray(normal, dtype=np.int64))
    _, _, quotient_order = _quotient(group.cayley_table, np.asarray(normal, dtype=np.int64))
    return SplitResult(
        splits=complement is not None,
        complement=complement,
        quotient_order=quotient_order,
        method="backtracking-complement",
    )


def trivialising_transversal(group: FiniteGroup, normal: np.ndarray) -> np.ndarray | None:
    """A transversal ``s`` with ``f == e`` (the complement, as a ``Q -> G`` map),
    or ``None`` when the extension does not split."""
    result = split_status(group, normal)
    if result.complement is None:
        return None
    coset_label, _, quotient_order = _quotient(
        group.cayley_table, np.asarray(normal, dtype=np.int64)
    )
    transversal = np.empty(quotient_order, dtype=np.int64)
    for g in result.complement:
        transversal[int(coset_label[g])] = g
    return transversal


@dataclass(frozen=True)
class CocycleFit:
    """The ``f == 1`` fit (I-22 twisted-rule fit at the ground-truth level).

    ``untwisted_accuracy`` is the fraction of products the untwisted
    (semidirect) rule reproduces under the best available transversal; it is
    1.0 iff the extension splits. ``twisted_accuracy`` is always 1.0 (the
    twisted rule is exact). ``splits`` records the group-theoretic determination
    (``f == 1`` achievable iff split), which is decisive independently of the
    fit residual.
    """

    splits: bool
    untwisted_accuracy: float
    twisted_accuracy: float
    quotient_order: int
    normal_order: int
    used_trivialising_transversal: bool

    def to_record(self) -> dict[str, Any]:
        return {
            "splits": self.splits,
            "untwisted_accuracy": self.untwisted_accuracy,
            "twisted_accuracy": self.twisted_accuracy,
            "quotient_order": self.quotient_order,
            "normal_order": self.normal_order,
            "used_trivialising_transversal": self.used_trivialising_transversal,
        }


def f_equiv_one_fit(group: FiniteGroup, normal: np.ndarray) -> CocycleFit:
    """The decisive split-vs-non-split discriminator: does the untwisted
    (``f == 1``) rule reproduce the whole Cayley table?

    On a *split* extension the complement transversal makes the untwisted rule
    exact -- the fit SUCCEEDS (accuracy 1.0). On a *non-split* extension no
    transversal trivialises ``f``, so the untwisted rule fails for every
    transversal -- the fit FAILS (accuracy < 1.0). This is the GL(2,3) [split]
    vs SL(2,3).C2 [non-split] contrast.
    """
    table = group.cayley_table
    normal_array = np.asarray(normal, dtype=np.int64)
    transversal = trivialising_transversal(group, normal_array)
    splits = transversal is not None
    extension = build_extension(group, normal_array, transversal)
    untwisted = coordinate_product_accuracy(extension, table, include_cocycle=False)
    twisted = coordinate_product_accuracy(extension, table, include_cocycle=True)
    if splits and untwisted < 1.0 - _TOL:
        raise ValueError("split extension but the trivialising transversal did not trivialise f")
    if not splits and untwisted > 1.0 - _TOL:
        raise ValueError("non-split extension but the untwisted rule was exact")
    return CocycleFit(
        splits=splits,
        untwisted_accuracy=untwisted,
        twisted_accuracy=twisted,
        quotient_order=extension.quotient_order,
        normal_order=extension.normal_order,
        used_trivialising_transversal=splits,
    )


# ---------------------------------------------------------------------------
# I-22 / I-22b: model-facing cocycle probe and ablation
# ---------------------------------------------------------------------------


def pair_features(model: GroupModel, order: int, *, site: str = "resid_final") -> np.ndarray:
    """Per-pair activation vectors over the whole Cayley grid, read at the '='
    position (-1): ``[|G|^2, d]`` for ``site in {"resid_final", "mlp_post"}``.

    Rows follow ``cayley_grid_tokens`` order (row ``k = (k // n, k % n)``).
    """
    if site not in ("resid_final", "mlp_post"):
        raise ValueError(f"site must be 'resid_final' or 'mlp_post', got {site!r}")
    tokens = cayley_grid_tokens(order)
    model.eval()
    rows: list[torch.Tensor] = []
    with torch.no_grad():
        for start in range(0, tokens.shape[0], 8192):
            cache = model(tokens[start : start + 8192], return_cache=True)
            value = cache[site]
            if value is None:
                raise ValueError(f"model has no {site} (use_mlp=false?)")
            rows.append(value[:, -1, :].detach().to(torch.float64).cpu())
    return torch.cat(rows, dim=0).numpy()


def cell_labels(extension: Extension, order: int) -> tuple[np.ndarray, np.ndarray]:
    """Per grid-row ``(q1, q2)`` cell id and the cocycle value ``f(q1, q2)``.

    ``cell`` is ``q1 * |Q| + q2`` (the pseudoreplication unit -- many ``(a, b)``
    rows share one cell); ``f_label`` is the local ``N`` index of ``f(q1, q2)``.
    """
    grid = np.arange(order)
    a = np.repeat(grid, order)
    b = np.tile(grid, order)
    q1 = extension.coset_label[a]
    q2 = extension.coset_label[b]
    cell = q1 * extension.quotient_order + q2
    f_label = extension.cocycle[q1, q2]
    return cell.astype(np.int64), f_label.astype(np.int64)


def _ridge_multiclass(
    x_train: np.ndarray, y_train: np.ndarray, x_test: np.ndarray, classes: np.ndarray, lam: float
) -> np.ndarray:
    """Closed-form ridge one-vs-all decode; returns predicted class per test row.

    A bias column is appended; the penalty ``lam`` is not applied to it.
    """
    n_features = x_train.shape[1]
    xb = np.hstack([x_train, np.ones((x_train.shape[0], 1))])
    onehot = (y_train[:, None] == classes[None, :]).astype(np.float64)
    penalty = lam * np.eye(n_features + 1)
    penalty[-1, -1] = 0.0
    weights = np.linalg.solve(xb.T @ xb + penalty, xb.T @ onehot)
    xtb = np.hstack([x_test, np.ones((x_test.shape[0], 1))])
    scores = xtb @ weights
    return classes[scores.argmax(axis=1)]


def _balanced_accuracy(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    recalls = []
    for cls in np.unique(y_true):
        mask = y_true == cls
        recalls.append(float((y_pred[mask] == cls).mean()))
    return float(np.mean(recalls))


@dataclass(frozen=True)
class ProbeResult:
    """I-22 cocycle-value probe, held out over ``(q1, q2)`` cells.

    ``defined`` is False on a split member with the complement transversal:
    ``f`` is constant, the decode target is degenerate, and the control is a fit
    residual, not a probe score (the record says ``UNDEFINED``). ``accuracy`` is
    over held-out cell rows; ``balanced_accuracy`` is the chance-corrected form;
    ``chance`` is the majority-class rate on the held-out rows.
    """

    defined: bool
    site: str
    n_cells: int
    n_classes: int
    accuracy: float | None
    balanced_accuracy: float | None
    chance: float | None
    reason: str | None = None

    def to_record(self) -> dict[str, Any]:
        if not self.defined:
            return {"instrument": "cocycle_probe", "status": "UNDEFINED", "reason": self.reason}
        return {
            "instrument": "cocycle_probe",
            "status": "measured",
            "site": self.site,
            "n_cells": self.n_cells,
            "n_classes": self.n_classes,
            "accuracy": self.accuracy,
            "balanced_accuracy": self.balanced_accuracy,
            "chance": self.chance,
        }


def probe_cocycle(
    features: np.ndarray,
    extension: Extension,
    order: int,
    *,
    site: str = "resid_final",
    lam: float = 1.0,
) -> ProbeResult:
    """Decode ``f(q1, q2)`` from per-pair ``features``, held out over cells.

    Leave-one-cell-out: for each ``(q1, q2)`` cell, train the ridge decode on the
    rows of every *other* cell and predict the held-out cell's rows, so a cell's
    label is never seen in its own training fold. Degenerate (constant ``f``)
    targets return ``UNDEFINED`` -- the split member's control.
    """
    cell, f_label = cell_labels(extension, order)
    distinct_f = np.unique(f_label)
    if distinct_f.size < 2:
        return ProbeResult(
            defined=False,
            site=site,
            n_cells=int(np.unique(cell).size),
            n_classes=int(distinct_f.size),
            accuracy=None,
            balanced_accuracy=None,
            chance=None,
            reason="cocycle is constant (split member with the complement transversal): "
            "the decode target is degenerate, so the control is a fit residual not a probe score",
        )
    cells = np.unique(cell)
    preds = np.empty(features.shape[0], dtype=np.int64)
    preds.fill(-1)
    for held in cells:
        test_mask = cell == held
        train_mask = ~test_mask
        train_classes = np.unique(f_label[train_mask])
        preds[test_mask] = _ridge_multiclass(
            features[train_mask], f_label[train_mask], features[test_mask], train_classes, lam
        )
    accuracy = float((preds == f_label).mean())
    balanced = _balanced_accuracy(f_label, preds)
    _, counts = np.unique(f_label, return_counts=True)
    chance = float(counts.max() / counts.sum())
    return ProbeResult(
        defined=True,
        site=site,
        n_cells=int(cells.size),
        n_classes=int(distinct_f.size),
        accuracy=accuracy,
        balanced_accuracy=balanced,
        chance=chance,
    )


def _unembed(model: GroupModel) -> np.ndarray:
    return model.W_U.detach().to(torch.float64).cpu().numpy()


def _grid_targets(group: FiniteGroup) -> np.ndarray:
    return group.cayley_table.reshape(-1)


@dataclass(frozen=True)
class AblationResult:
    """I-22b: ablation of the ``f``-carrying direction vs a matched random one.

    ``defined`` is False on a split member (no ``f`` direction to remove).
    ``delta_accuracy`` is the drop in full-grid argmax accuracy caused by
    removing the decoded ``f``-subspace at ``site``; ``random_delta_accuracy`` is
    the same for a norm/dimension-matched random subspace (I-03). A larger
    ``f``-subspace drop than the random control is what licenses "the model uses
    the cocycle"; the record is estimation-first (effect sizes, no threshold).
    """

    defined: bool
    site: str
    subspace_dim: int
    baseline_accuracy: float | None
    delta_accuracy: float | None
    random_delta_accuracy: float | None
    reason: str | None = None

    def to_record(self) -> dict[str, Any]:
        if not self.defined:
            return {"instrument": "cocycle_ablation", "status": "UNDEFINED", "reason": self.reason}
        return {
            "instrument": "cocycle_ablation",
            "status": "measured",
            "site": self.site,
            "subspace_dim": self.subspace_dim,
            "baseline_accuracy": self.baseline_accuracy,
            "delta_accuracy": self.delta_accuracy,
            "random_delta_accuracy": self.random_delta_accuracy,
        }


def _accuracy_from_features(
    features: np.ndarray, unembed: np.ndarray, targets: np.ndarray
) -> float:
    logits = features @ unembed
    return float((logits.argmax(axis=1) == targets).mean())


def cocycle_ablation(
    model: GroupModel,
    group: FiniteGroup,
    extension: Extension,
    *,
    subspace_dim: int | None = None,
    seed: int = 0,
) -> AblationResult:
    """I-22b: remove the decoded ``f``-direction at ``resid_final`` and measure
    the accuracy drop, against a norm/dimension-matched random subspace.

    The ``f``-subspace is the leading right-singular directions of the
    class-mean matrix of ``f`` over cells (the directions along which the mean
    ``resid_final`` moves with ``f``). Both architectures compute
    ``logits = resid_final @ W_U``, so ablation is exact by projecting the
    subspace out of ``resid_final`` and re-reading the logits.
    """
    features = pair_features(model, group.order, site="resid_final")
    _, f_label = cell_labels(extension, group.order)
    distinct = np.unique(f_label)
    if distinct.size < 2:
        return AblationResult(
            defined=False,
            site="resid_final",
            subspace_dim=0,
            baseline_accuracy=None,
            delta_accuracy=None,
            random_delta_accuracy=None,
            reason="cocycle is constant (split member): no f-direction exists to ablate",
        )
    unembed = _unembed(model)
    targets = _grid_targets(group)
    baseline = _accuracy_from_features(features, unembed, targets)

    # Class means of resid_final by f value, centred: their span is the
    # f-carrying subspace.
    grand = features.mean(axis=0, keepdims=True)
    means = np.stack([features[f_label == cls].mean(axis=0) for cls in distinct]) - grand
    _, _, vh = np.linalg.svd(means, full_matrices=False)
    dim = min(subspace_dim or (distinct.size - 1), vh.shape[0])
    basis = vh[:dim]  # [dim, d]
    projected = features - (features @ basis.T) @ basis
    delta = baseline - _accuracy_from_features(projected, unembed, targets)

    # Norm/dimension-matched random subspace control (I-03).
    rng = np.random.default_rng(seed)
    random_basis = rng.standard_normal((dim, features.shape[1]))
    q_basis, _ = np.linalg.qr(random_basis.T)
    q_basis = q_basis[:, :dim].T
    projected_rand = features - (features @ q_basis.T) @ q_basis
    random_delta = baseline - _accuracy_from_features(projected_rand, unembed, targets)

    return AblationResult(
        defined=True,
        site="resid_final",
        subspace_dim=dim,
        baseline_accuracy=baseline,
        delta_accuracy=delta,
        random_delta_accuracy=random_delta,
    )


__all__ = [
    "AblationResult",
    "CocycleFit",
    "Extension",
    "ProbeResult",
    "SplitResult",
    "build_extension",
    "cell_labels",
    "cocycle_ablation",
    "cocycle_is_trivial",
    "coordinate_product_accuracy",
    "coordinates",
    "f_equiv_one_fit",
    "is_normal",
    "is_subgroup",
    "pair_features",
    "probe_cocycle",
    "split_status",
    "subgroup_closure",
    "trivialising_transversal",
]
