"""Small, deterministic group artifacts used only by the Python test suite.

Production group data is exported by Sage/GAP and is deliberately not kept in
the repository.  These fixtures exercise the same serialized-artifact boundary
without making the offline unit suite depend on a generated corpus or Sage.
"""

from __future__ import annotations

import json
import os
import tempfile
from collections.abc import Callable
from pathlib import Path

import numpy as np


def _inverse(table: np.ndarray) -> np.ndarray:
    return np.array([int(np.flatnonzero(table[i] == 0)[0]) for i in range(len(table))])


def _classes(table: np.ndarray) -> list[np.ndarray]:
    inverse = _inverse(table)
    remaining = set(range(len(table)))
    result: list[np.ndarray] = []
    while remaining:
        x = min(remaining)
        cls = {int(table[table[g, x], inverse[g]]) for g in range(len(table))}
        result.append(np.array(sorted(cls), dtype=np.int64))
        remaining -= cls
    return result


def _cyclic_closure(table: np.ndarray, generator: int) -> frozenset[int]:
    """The subgroup generated by a single element: {e, g, g*g, g*g*g, ...}.

    Exact and complete only for a CYCLIC group -- every subgroup of a cyclic
    group is generated by a single element, so closing each element under
    repeated table application visits every subgroup exactly once (per
    divisor of the group order). A general non-cyclic group can have
    subgroups needing more than one generator; callers must not use this
    outside the cyclic case.
    """
    members = {0}
    current = 0
    while True:
        current = int(table[current, generator])
        if current in members:
            break
        members.add(current)
    return frozenset(members)


def _subgroups(table: np.ndarray) -> list[np.ndarray]:
    """Enumerate subgroups of the test fixture groups.

    For n <= 8 (the dihedral and quaternion fixtures, which are not cyclic)
    this brute-forces every subset via a 2^n mask scan -- infeasible past
    n≈20, but fine at this size. For n > 8, every fixture reached by this
    branch is cyclic (see ``write_test_artifacts``'s call sites: (21, 2) and
    (32, 1) are the only n > 8 groups constructed), so the O(n^2)
    single-generator-closure method below is exact and complete with no
    mask scan needed. The assertion below catches a future non-cyclic n > 8
    fixture loudly instead of silently shipping an incomplete subgroup list.
    """
    n = len(table)
    if n > 8:
        closures = {_cyclic_closure(table, g) for g in range(n)}
        result = [np.array(sorted(members), dtype=np.int64) for members in closures]
        result.sort(key=lambda members: (len(members), members.tolist()))
        orders = sorted(len(members) for members in result)
        divisors = sorted(d for d in range(1, n + 1) if n % d == 0)
        assert orders == divisors, (
            f"cyclic subgroup enumeration for n={n} produced orders {orders}, "
            f"expected exactly the divisors of n: {divisors}"
        )
        return result
    result = []
    for mask in range(1, 1 << n):
        if not mask & 1:
            continue
        members = np.array([i for i in range(n) if mask & (1 << i)], dtype=np.int64)
        if all(int(table[a, b]) in members for a in members for b in members):
            result.append(members)
    return result


def _cosets(table: np.ndarray, subgroup: np.ndarray) -> list[np.ndarray]:
    unseen = set(range(len(table)))
    output: list[np.ndarray] = []
    while unseen:
        representative = min(unseen)
        coset = np.array(sorted({int(table[representative, h]) for h in subgroup}), dtype=np.int64)
        output.append(coset)
        unseen -= set(coset.tolist())
    return output


def _projector(table: np.ndarray, character: np.ndarray, dimension: int) -> np.ndarray:
    inverse = _inverse(table)
    n = len(table)
    return np.array(
        [
            [dimension / n * character[table[inverse[left], right]] for right in range(n)]
            for left in range(n)
        ],
        dtype=np.complex128,
    )


def _cyclic(n: int) -> tuple[np.ndarray, list[np.ndarray], list[np.ndarray], list[int], list[str]]:
    table = (np.add.outer(np.arange(n), np.arange(n)) % n).astype(np.int64)
    values = np.arange(n)
    chars = [np.exp(2j * np.pi * k * values / n) for k in range(n)]
    matrices = [char[:, None, None] for char in chars]
    fs = [1 if k == 0 or (n % 2 == 0 and k == n // 2) else 0 for k in range(n)]
    fields = ["real" if value else "complex" for value in fs]
    return table, matrices, chars, fs, fields


def _dihedral(
    m: int,
) -> tuple[np.ndarray, list[np.ndarray], list[np.ndarray], list[int], list[str]]:
    # Elements are r^k s^b, with s r s = r^-1.
    n = 2 * m
    table = np.empty((n, n), dtype=np.int64)
    for left in range(n):
        k, b = left % m, left // m
        for right in range(n):
            right_rotation, right_reflection = right % m, right // m
            table[left, right] = ((k + (-1 if b else 1) * right_rotation) % m) + m * (
                (b + right_reflection) % 2
            )
    rotations = np.array(
        [
            [
                [np.cos(2 * np.pi * k / m), -np.sin(2 * np.pi * k / m)],
                [np.sin(2 * np.pi * k / m), np.cos(2 * np.pi * k / m)],
            ]
            for k in range(m)
        ]
    )
    reflection = np.diag([1.0, -1.0])
    two_d = np.array(
        [rotations[i % m] @ (reflection if i // m else np.eye(2)) for i in range(n)],
        dtype=np.complex128,
    )
    matrices: list[np.ndarray] = []
    chars: list[np.ndarray] = []
    # When m is odd, r must map to +1 in every one-dimensional representation.
    for r_sign in (1, -1) if m % 2 == 0 else (1,):
        for s_sign in (1, -1):
            values = np.array(
                [r_sign ** (i % m) * s_sign ** (i // m) for i in range(n)], dtype=np.complex128
            )
            matrices.append(values[:, None, None])
            chars.append(values)
    matrices.append(two_d)
    chars.append(np.trace(two_d, axis1=1, axis2=2))
    return table, matrices, chars, [1] * len(chars), ["real"] * len(chars)


def _quaternion() -> tuple[np.ndarray, list[np.ndarray], list[np.ndarray], list[int], list[str]]:
    # 1, -1, i, -i, j, -j, k, -k; (sign, basis) multiplication.
    basis_product = {
        (0, 0): (1, 0),
        (0, 1): (1, 1),
        (0, 2): (1, 2),
        (0, 3): (1, 3),
        (1, 0): (1, 1),
        (2, 0): (1, 2),
        (3, 0): (1, 3),
        (1, 1): (-1, 0),
        (2, 2): (-1, 0),
        (3, 3): (-1, 0),
        (1, 2): (1, 3),
        (2, 3): (1, 1),
        (3, 1): (1, 2),
        (2, 1): (-1, 3),
        (3, 2): (-1, 1),
        (1, 3): (-1, 2),
    }
    elements = [(1, 0), (-1, 0), (1, 1), (-1, 1), (1, 2), (-1, 2), (1, 3), (-1, 3)]
    index = {element: i for i, element in enumerate(elements)}
    table = np.empty((8, 8), dtype=np.int64)
    for a, (sa, ba) in enumerate(elements):
        for b, (sb, bb) in enumerate(elements):
            sign, basis = basis_product[ba, bb]
            table[a, b] = index[(sa * sb * sign, basis)]
    i_matrix = np.diag([1j, -1j])
    j_matrix = np.array([[0, 1], [-1, 0]], dtype=np.complex128)
    k_matrix = i_matrix @ j_matrix
    two_d = np.array(
        [np.eye(2), -np.eye(2), i_matrix, -i_matrix, j_matrix, -j_matrix, k_matrix, -k_matrix]
    )
    matrices: list[np.ndarray] = []
    chars: list[np.ndarray] = []
    for i_sign in (1, -1):
        for j_sign in (1, -1):
            values = np.array(
                [1, 1, i_sign, i_sign, j_sign, j_sign, i_sign * j_sign, i_sign * j_sign],
                dtype=np.complex128,
            )
            matrices.append(values[:, None, None])
            chars.append(values)
    matrices.append(two_d)
    chars.append(np.trace(two_d, axis1=1, axis2=2))
    return (
        table,
        matrices,
        chars,
        [1, 1, 1, 1, -1],
        ["real", "real", "real", "real", "quaternionic"],
    )


def _atomic_savez(path: Path, arrays: dict[str, np.ndarray]) -> None:
    """Write ``arrays`` to ``path`` as an .npz file without a torn-read window.

    ``np.savez`` truncates the target file and streams the new zip content
    into it, leaving a window where a concurrent reader sees an empty or
    partial file (``zipfile.BadZipFile`` / ``EOFError``). Build the complete
    file under a unique temporary name in the *same directory* as ``path``
    (same filesystem is required for ``os.replace`` to be atomic), then
    atomically rename it into place -- ``os.replace`` is atomic on POSIX and
    Windows (unlike ``os.rename``), so a reader always sees a complete file.
    """
    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=f"{path.stem}.", suffix=".npz.tmp")
    try:
        with os.fdopen(fd, "wb") as handle:
            # A file handle (not a path) stops np.savez from appending its
            # own ".npz" suffix to the already-suffixed temporary filename.
            np.savez(handle, **arrays)
        os.replace(tmp_name, path)
    except BaseException:
        Path(tmp_name).unlink(missing_ok=True)
        raise


def _write_group(
    path: Path,
    order: int,
    index: int,
    builder: Callable[
        [], tuple[np.ndarray, list[np.ndarray], list[np.ndarray], list[int], list[str]]
    ],
) -> None:
    table, matrices, characters, fs, fields = builder()
    classes = _classes(table)
    subgroups = _subgroups(table)
    class_values = np.array([[char[cls[0]] for cls in classes] for char in characters])
    # Each block carries (projector, irrep_degree, block_rank, irrep_indices).
    # ``irrep_degree`` is chi(e) = d, shared by both members of a merged
    # conjugate pair; ``block_rank`` is the isotypic component's dimension in
    # the regular representation, sum_i d_i^2 == trace(P) -- d^2 for a single
    # real irrep, 2*d^2 for a merged conjugate pair. Equal only when d == 1,
    # so the exporter and these fixtures must both keep them apart.
    blocks: list[tuple[np.ndarray, int, int, tuple[int, ...]]] = []
    used: set[int] = set()
    for i, char in enumerate(characters):
        if i in used:
            continue
        conjugate = next(
            (j for j, other in enumerate(characters) if np.allclose(other, char.conjugate())), i
        )
        projector = _projector(table, char, matrices[i].shape[1])
        indices = (i,)
        if conjugate != i:
            projector += _projector(table, characters[conjugate], matrices[conjugate].shape[1])
            indices = (i, conjugate)
            used.add(conjugate)
        used.add(i)
        real = np.real_if_close(projector, tol=1000).real
        degree = int(matrices[i].shape[1])
        rank = sum(int(matrices[j].shape[1]) ** 2 for j in indices)
        if abs(float(np.trace(real)) - rank) > 1e-8:
            raise AssertionError(
                f"fixture block {indices}: trace(P)={float(np.trace(real)):.6f} != sum d^2 = {rank}"
            )
        # ``_projector`` computes chi(x^-1 y) without conjugating chi, correct
        # only because complex-conjugate character pairs are merged into one
        # real block (above) before this point -- an unmerged non-self-
        # conjugate complex irrep block would silently produce a wrong
        # (non-idempotent) projector. Guard the invariant directly: a genuine
        # projector satisfies P@P == P.
        if not np.allclose(real @ real, real):
            raise AssertionError(
                f"fixture block {indices}: projector is not idempotent (P@P != P) -- "
                "likely an unmerged complex irrep fed to _projector without conjugation"
            )
        blocks.append((real, degree, rank, indices))
    metadata = {
        "format": 2,
        "small_group": [order, index],
        "order": order,
        "description": f"test fixture SmallGroup({order},{index})",
        "element_labels": [str(i) for i in range(order)],
        "classes": len(classes),
        "subgroups": len(subgroups),
        "coset_counts": [len(_cosets(table, s)) for s in subgroups],
        "irreps": [
            {"dimension": matrix.shape[1], "field": field, "basis": "test-fixture"}
            for matrix, field in zip(matrices, fields, strict=True)
        ],
        "blocks": [
            {"irrep_degree": degree, "block_rank": rank, "irrep_indices": list(indices)}
            for _, degree, rank, indices in blocks
        ],
        "provenance": {"backend": "test fixture", "purpose": "offline unit tests"},
    }
    arrays: dict[str, np.ndarray] = {
        "metadata": np.array(json.dumps(metadata)),
        "cayley_table": table,
        "character_real": class_values.real,
        "character_imag": class_values.imag,
        "frobenius_schur": np.array(fs, dtype=np.int64),
    }
    for i, cls in enumerate(classes):
        arrays[f"class_{i}"] = cls
    for i, matrix in enumerate(matrices):
        arrays[f"irrep_{i}_real"], arrays[f"irrep_{i}_imag"] = matrix.real, matrix.imag
        arrays[f"irrep_{i}_character_real"], arrays[f"irrep_{i}_character_imag"] = (
            characters[i].real,
            characters[i].imag,
        )
    for i, (projector, _, _, _) in enumerate(blocks):
        arrays[f"block_{i}_projector"] = projector
    for i, subgroup in enumerate(subgroups):
        arrays[f"subgroup_{i}"] = subgroup
        for j, coset in enumerate(_cosets(table, subgroup)):
            arrays[f"coset_{i}_{j}"] = coset
    _atomic_savez(path, arrays)


def write_test_artifacts(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    cyclic = {(2, 1): 2, (4, 1): 4, (6, 2): 6, (7, 1): 7, (8, 1): 8, (21, 2): 21, (32, 1): 32}
    for (order, index), n in cyclic.items():
        _write_group(
            directory / f"smallgroup_{order}_{index}.npz", order, index, lambda n=n: _cyclic(n)
        )
    _write_group(directory / "smallgroup_6_1.npz", 6, 1, lambda: _dihedral(3))
    _write_group(directory / "smallgroup_8_3.npz", 8, 3, lambda: _dihedral(4))
    _write_group(directory / "smallgroup_8_4.npz", 8, 4, _quaternion)
